### PR TITLE
Dal

### PR DESCRIPTION
**Pull request by Quecky**
@Git-Friends-FI/blue-team I want to do a merge please review my code

### CODE REVIEW

**Comment by SaladinoBelisario** [comment]
@Stefany-Ag please review this

**Comment by Quecky** [comment]
@SaladinoBelisario please help me

**Comment by SaladinoBelisario** [comment]
@Git-Friends-FI/red-team common girls

**Review by Stefany-Ag — APPROVED** [review]

**Review by SaladinoBelisario — APPROVED** [review]
Commit aproved, good recipe

**Pull request merged**
